config/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.views.generic import TemplateView


# pylint: disable=invalid-name
urlpatterns = [
    url('', include('social_django.urls', namespace='social')),
    url(r'^fittings/', include('iron_at.fittings.urls', namespace='fittings')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='index'),
    url(r'^admin/', admin.site.urls),
]
# pylint: enable=invalid-name

iron_at/fittings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.IndexView.as_view(),
        name='index'),
    url(r'^create/$',
        views.CompositionCreateView.as_view(),
        name='composition-create'),
    url(r'^(?P<pk>\d+)/$',
        views.CompositionDetailsView.as_view(),
        name='composition-details'),
    url(r'^(?P<pk>\d+)/edit/$',
        views.CompositionEditView.as_view(),
        name='composition-edit'),
    url(r'^(?P<pk>\d+)/delete/$',
        views.CompositionDeleteView.as_view(),
        name='composition-delete'),
    url(r'^(?P<comp_id>\d+)/fit/create/$',
        views.FitCreateView.as_view(),
        name='fit-create'),
    url(r'^(?P<comp_id>\d+)/fit/(?P<pk>\d+)/edit/$',
        views.FitEditView.as_view(),
        name='fit-edit'),
    url(r'^(?P<comp_id>\d+)/fit/(?P<pk>\d+)/delete/$',
        views.FitDeleteView.as_view(),
        name='fit-delete'),
    url(r'^(?P<comp_id>\d+)/fit/(?P<fit_id>\d+)/xup/$',
        views.XUpView.as_view(),
        name='fit-xup'),
]
#pylint: enable=invalid-name

iron_at/eveauth/models.py
"""The database models to enable EVE Authentication.

Copyright (c) 2017, Arun Seehra <seehra.a@gmail.com>
All rights reserved.
"""

from django.contrib.auth.models import AbstractUser

# Create your models here.
class EveUser(AbstractUser):
    """A placeholder for a custom user model.
    
    For now, it is not necessary to have any additional field, we just need
    a user name. Eventually we might want to extend this, so having this will
    enable that.
    """
    pass

iron_at/fittings/models.py
"""The database models for the fittings manager.

Copyright (c) 2017, Arun Seehra <seehra.a@gmail.com>
All rights reserved.
"""
import re

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.shortcuts import reverse


class Composition(models.Model):
    """The representation of a AT Fleet Composition.

    Attributes:
        name: The name of the fleet comp.
        description: User added details about the composition.
        owner: The user that this composition, or null if the user has been
            subsequently deleted.
        fits: The RelatedManager for Fit entries associated with this fleet
            comp.
    """

    name = models.CharField(max_length=80)
    description = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, models.SET_NULL, null=True)

    class Meta:  # pylint: disable=too-few-public-methods,missing-docstring
        default_permissions = ('view', 'add', 'change', 'delete')

    def get_absolute_url(self):
        """Get the URL form each object in order to allow generic views."""
        return reverse('fittings:composition-details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)


class Fit(models.Model):
    """The representation of an EVE Online ship fit.

    Attributes:
        comp: The fleet comp this fit belongs to. Can be null to allow for
            testing.
        eft_fit: An EFT-formatted string that describes the fit.
        quantity: The number of ships of this fit that should appear in the
            fleet comp.
        num_skill: The number of hull skills. E.g. a Kitsune has two skills:
            Caldari Frigate and Electronic Attack Ships. This is brittle as
            it does not handle T3 cruisers properly.
        x_ups: The RelatedManager for XUp entries associated with this fit.
        skills: The RelatedManager for FitSkill entries associated with this
            fit.
    """

    comp = models.ForeignKey(Composition, models.CASCADE, related_name='fits', null=True)
    eft_fit = models.TextField()
    quantity = models.SmallIntegerField(validators=[MinValueValidator(1),
                                                    MaxValueValidator(2)])

    class Meta:  # pylint: disable=too-few-public-methods,missing-docstring
        default_permissions = ('view', 'add', 'change', 'delete')

    def ship_name(self):
        """Return the ship hull used for this ship."""
        matches = re.search(r'\[([\w\d\s]+)(,.*)?\]', str(self.eft_fit).splitlines()[0])
        if matches:
            return matches.group(1).title()
        return None

    def __str__(self):
        return '{}.{}'.format(self.comp, self.ship_name())


class FitSkill(models.Model):
    """The skill needed to fly a particular fit.

    Attributes:
        skill_name: The name of the skill, e.g. "Caldari Frigate."
        fit: The fit (and thus ship) that this skill corresponds to.
    """

    skill_name = models.CharField(max_length=80)
    fit = models.ForeignKey(Fit, models.CASCADE, related_name='skills')

    class Meta:  # pylint: disable=too-few-public-methods,missing-docstring
        default_permissions = ('view', 'add', 'change', 'delete')

    def __str__(self):
        return "{} - {}".format(self.fit, self.skill_name)


class XUp(models.Model):
    """The representation of a pilot signing up for a particular fit.

    Attributes:
        pilot: The user that has signed up.
        fit: The fit to be signed up for.
        t2_capable: Whether the pilot is capable of flying the fit with all T2
            modules.
        skills: a ManyToMany relationship between XUps and FitSkills with extra
            data provided in XUpSkill.
    """

    pilot = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    fit = models.ForeignKey(Fit, models.CASCADE, related_name='x_ups')
    t2_capable = models.BooleanField()
    skills = models.ManyToManyField(FitSkill, through='XUpSkill')

    class Meta:  # pylint: disable=too-few-public-methods,missing-docstring
        default_permissions = ('view', 'add', 'change', 'delete')

    def min_skill(self):
        """Get the loweset skill value associated with this fit."""
        # pylint: disable=no-member
        skills = [skill.skill_value for skill in self.xupskill_set.all()]
        # pylint: enable=no-member
        return min(skills)

    def __str__(self):
        return '{} - {}'.format(self.fit, self.pilot.get_full_name())


class XUpSkill(models.Model):
    """The representation of a pilot's skills with regard to a fit.

    Attributes:
        x_up: The signup that this entry corresponds with.
        skill: The skill that this entry corresponds with.
        skill_value: The pilot's skill level.
    """

    x_up = models.ForeignKey(XUp, models.CASCADE)
    skill = models.ForeignKey(FitSkill, models.CASCADE)
    skill_value = models.SmallIntegerField(validators=[MinValueValidator(0),
                                                       MaxValueValidator(5)])

    class Meta:  # pylint: disable=too-few-public-methods,missing-docstring
        default_permissions = ('view', 'add', 'change', 'delete')

    def __str__(self):
        return str(self.skill)

iron_at/fittings/forms.py
"""Custom forms for fitting manager.

Copyright (c) 2017, Arun Seehra <seehra.a@gmail.com>
All rights reserved.
"""

from django import forms
from django.forms import inlineformset_factory

from .models import Fit, FitSkill

# pylint: disable=invalid-name
FitSkillFormSet = inlineformset_factory(Fit, FitSkill, fields=['skill_name'])
# pylint: enable=invalid-name


class XUpForm(forms.Form):
    """A form for x-ing up for a particular fit"""

    sign_up = forms.BooleanField(required=False)
    t2_capable = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super(XUpForm, self).clean()
        if not cleaned_data.get('sign_up'):
            return cleaned_data

        skill_field_keys = [key for key in cleaned_data.copy().keys()
                            if key.startswith('skill_')]
        for field_name in skill_field_keys:
            if cleaned_data[field_name] is None:
                self.add_error(field_name, 'Required field.')

iron_at/fittings/views.py
# pylint: disable=too-many-ancestors

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  ListView, TemplateView, UpdateView)

from .forms import FitSkillFormSet, XUpForm
from .models import Composition, Fit, XUp, XUpSkill


class CompositionCreateView(PermissionRequiredMixin, CreateView):
    """Simple generic view to create a new fleet comp."""

    model = Composition
    fields = ['name', 'description']
    permission_required = 'fittings.add_composition'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CompositionCreateView, self).form_valid(form)


class CompositionEditView(PermissionRequiredMixin, UpdateView):
    """Simple generic view to edit an existing fleet comp."""

    model = Composition
    fields = ['name', 'description']
    permission_required = 'fittings.change_composition'


class CompositionDetailsView(PermissionRequiredMixin, DetailView):
    """Simple generic view to display a fleet comp."""

    model = Composition
    permission_required = ['fittings.view_composition', 'fittings.view_fit']


class CompositionDeleteView(PermissionRequiredMixin, DeleteView):
    """Simple generic view to delete a fleet comp."""

    model = Composition
    success_url = reverse_lazy('fittings:index')
    permission_required = 'fittings.delete_composition'


class IndexView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Simple generic view for displaying all the fleet comps."""

    model = Composition
    template_name = 'fittings/index.html'
    permission_required = 'fittings.view_composition'


class FitCreateView(PermissionRequiredMixin, CreateView):
    """View for adding a fit to a fleet composition"""
    model = Fit
    fields = ['eft_fit', 'quantity']
    permission_required = ['fittings.add_fit', 'fittings.add_fitskill']

    def get(self, request, *args, **kwargs):
        self.skills_formset = FitSkillFormSet(instance=Fit())
        return super(FitCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.skills_formset = FitSkillFormSet(request.POST, instance=Fit())
        return super(FitCreateView, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FitCreateView, self).get_context_data(**kwargs)
        comp = Composition.objects.get(pk=self.kwargs['comp_id'])
        context['composition'] = comp
        context['skills_formset'] = self.skills_formset
        return context

    def form_valid(self, form):
        form.instance.comp = Composition.objects.get(pk=self.kwargs['comp_id'])
        self.object = form.save()
        self.skills_formset = FitSkillFormSet(self.request.POST, instance=self.object)
        if not self.skills_formset.is_valid():
            return self.form_invalid(form)
        self.skills_formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('fittings:composition-details', args=[self.kwargs['comp_id']])


class FitEditView(PermissionRequiredMixin, UpdateView):
    """View for updating a fit's details."""

    model = Fit
    fields = ['eft_fit', 'quantity']
    permission_required = ['fittings.change_fit',
                           'fittings.add_fitskill',
                           'fittings.delete_fitskill',
                           'fittings.change_fitskill']

    def get(self, request, *args, **kwargs):
        self.skills_formset = FitSkillFormSet(instance=self.get_object())
        return super(FitEditView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.skills_formset = FitSkillFormSet(request.POST,
                                              instance=self.get_object())
        return super(FitEditView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        if not self.skills_formset.is_valid():
            return self.form_invalid(form)
        self.object = form.save()
        self.skills_formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(FitEditView, self).get_context_data(**kwargs)
        comp = Composition.objects.get(pk=self.kwargs['comp_id'])
        context['composition'] = comp
        context['skills_formset'] = self.skills_formset
        return context

    def get_success_url(self):
        return reverse('fittings:composition-details', args=[self.kwargs['comp_id']])


class FitDeleteView(PermissionRequiredMixin, DeleteView):
    """A simple delete-confirmation view for Fits."""

    model = Fit
    success_url = reverse_lazy('fittings:index')
    permission_required = 'fittings.delete_fit'


def skill_id_str(skill):
    return 'skill_{}'.format(skill.id)


def build_initial(x_up):
    if not x_up:
        return None
    initial = {'sign_up': True,
               't2_capable': x_up.t2_capable}

    skill_id_values = {skill_id_str(skill.skill): skill.skill_value
                       for skill in x_up.xupskill_set.all()}

    initial.update(skill_id_values)
    return initial


class XUpView(FormView):
    template_name = 'fittings/xup.html'
    form_class = XUpForm

    def get_fit(self):
        return get_object_or_404(Fit, pk=self.kwargs['fit_id'])

    def get(self, request, *args, **kwargs):
        self.fit = self.get_fit()
        return super(XUpView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.fit = self.get_fit()
        return super(XUpView, self).post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super(XUpView, self).get_form(form_class)
        # At this point, the form is fully initialized, so we can add our custom
        # fields
        for skill in self.fit.skills.all():
            form.fields[skill_id_str(skill)] = forms.IntegerField(
                label=skill.skill_name,
                min_value=0,
                max_value=5,
                required=False)
        return form

    def get_initial(self):
        x_up = XUp.objects.filter(fit=self.fit, pilot=self.request.user).first()
        return build_initial(x_up)

    def get_context_data(self, **kwargs):
        if 'fit' not in kwargs:
            kwargs['fit'] = self.fit
        return super(XUpView, self).get_context_data(**kwargs)

    def get_success_url(self):
        return reverse('fittings:composition-details', args=[self.kwargs['comp_id']])

    def form_valid(self, form):
        if not form.has_changed():
            return HttpResponseRedirect(self.get_success_url())

        if not form.cleaned_data['sign_up']:
            XUp.objects.filter(fit=self.fit, pilot=self.request.user).delete()
            return HttpResponseRedirect(self.get_success_url())

        x_up, created = XUp.objects.update_or_create(
            fit=self.fit,
            pilot=self.request.user,
            defaults={'t2_capable': form.cleaned_data['t2_capable']})

        for skill in self.fit.skills.all():
            x_up_skill = XUpSkill.objects.update_or_create(
                x_up=x_up,
                skill=skill,
                defaults={'skill_value': form.cleaned_data[skill_id_str(skill)]})

        return HttpResponseRedirect(self.get_success_url())

iron_at/templates/fittings/base.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
<div class="collapse navbar-collapse" id="top-navbar-main">
  <ul class="nav navbar-nav">
    <li class="active">
      <a href="{% url 'fittings:index' %}">Fittings Manager <span class="sr-only"(current)</span></a>
    </li>
  </ul>
  {% if user.is_authenticated %}
  <p class="navbar-text navbar-right">
    <a class="navbar-link" href="{% url 'logout' %}">{{ user.first_name }} {{ user.last_name}}</a>
  </p>
  {% else %}
  <a class="navbar-btn navbar-right" href="{% url 'social:begin' backend='eveonline' %}?next={{ request.path }}">
    <img src="{% static 'img/EVE_SSO_Login_Buttons_Small_Black.png' %}"
          alt="Login with EVE Online">
  </a>
  {% endif %}
</div>
{% endblock %}

iron_at/templates/fittings/composition_confirm_delete.html
{% extends 'fittings/base.html' %}

{% block subtitle %}Delete {{ composition.name }}{% endblock %}

{% block body %}
<div class="page-header">
    <div class="alert alert-danger" role="alert">
      Are you sure that you would like the delete the following Fleet
      Composition?
    </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>{{ composition.name }}</h3>
  </div>
</div>
<div class="row button-footer">
  <div class="col-md-12">
    <form action="" method="post">
      {% csrf_token %}
      <a href="{% url 'fittings:composition-details' composition.id %}" class="btn btn-default">Cancel</a>
      <button class="btn btn-danger" type="submit">Confirm <i class="fa fa-trash-o fa-lg"></i></button>
    </form>
  </div>
</div>
{% endblock %}

iron_at/templates/fittings/composition_detail.html
{% extends 'fittings/base.html' %}

{% block subtitle %}{{ composition.name }}{% endblock %}

{% block body %}
<div class="page-header">
  <h1>
    {{ composition.name }}
    <small>
      {{ composition.owner.first_name }} {{ composition.owner.last_name }}
      <a href="{% url 'fittings:composition-edit' composition.id %}" title="Edit"><i class="fa fa-edit"></i></a>
    </small>
  </h1>
</div>
<div class="row">
  <div class="col-md-4">
    <ul class="list-group nav-list">
      {% for fit in composition.fits.all %}
      <li class="list-group-item" role="presentation">
        <a href="#{{ fit.ship_name|slugify }}">{{ fit.ship_name }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-md-8">
    {{ composition.description|linebreaks }}
  </div>
</div>
{% for fit in composition.fits.all %}
<div class="row">
  <div class="col-md-12">
    <h4 class="fit-header">
      <a class="anchor" id="{{ fit.ship_name|slugify }}"></a>
      {{ fit.ship_name }}{% if fit.quantity > 1 %} x{{ fit.quantity}}{% endif %}
      <small><a href="{% url 'fittings:fit-edit' comp_id=composition.id pk=fit.id %}" title="Edit">
        <i class="fa fa-edit"></i>
      </a></small>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <pre>{{ fit.eft_fit }}</pre>
  </div>
  <div class="col-md-6 col-md-offset-1">
    <table class="table">
      <thead>
      <tr>
        <th>Pilot</th>
        <th>T2</th>
        {% for skill in fit.skills.all %}
        <th>{{ skill.skill_name }}</th>
        {% endfor %}
      </tr>
      </thead>
      <tbody>
        {% for xup in fit.x_ups.all %}
        {% if xup.min_skill < 3 %}
        <tr class="danger">
        {% elif xup.min_skill == 3 %}
        <tr class="warning">
        {% elif xup.min_skill == 5 %}
        <tr class="success">
        {% else %}
        <tr>
        {% endif %}
          <td>{{ xup.pilot.first_name }} {{ xup.pilot.last_name }}</td>
          <td>
            {% if xup.t2_capable %}
              <i class="fa fa-check text-primary fa-fw" aria-label="True"></i>
            {% else %}
              <i class="fa fa-times text-danger fa-fw" aria-label="False"></i>
            {% endif %}
          </td>
          {% for skill in xup.xupskill_set.all %}
          <td>{{ skill.skill_value }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'fittings:fit-xup' comp_id=composition.id fit_id=fit.id %}" class="btn btn-default"><i class="fa fa-id-card-o fa-lg"></i> X-Up</a>
  </div>
</div>
{% endfor %}
<div class="row">
  <div class="col-md-12">
    <a href="{% url 'fittings:fit-create' composition.id %}">add fit</a>
  </div>
</div>
{% endblock %}

iron_at/templates/fittings/composition_form.html
{% extends 'fittings/base.html' %}
{% load bootstrap3 %}

{% block subtitle %}{% if object %}Edit{% else %}Create{% endif %} Composition{% endblock %}

{% block body %}
<div class="page-header">
  {% if object %}
  <h1>Update Composition:</h1>
  {% else %}
  <h1>Create Composition:</h1>
  {% endif %}
</div>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="row">
    <div class="col-md-6">
      {% bootstrap_field field %}
    </div>
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-md-6">
      {% if object %}
      <a href="{% url 'fittings:composition-details' object.id %}" class="btn btn-default">Cancel</a>
      {% else %}
      <a href="{% url 'fittings:index' %}" class="btn btn-default">Cancel</a>
      {% endif %}
      <div class="pull-right">
        {% if object %}
        <a href="{% url 'fittings:composition-delete' object.id %}" class="btn btn-danger">
          <i class="fa fa-trash-o fa-lg"></i> Delete
        </a>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</form>
{% endblock %}

iron_at/templates/fittings/fit_confirm_delete.html
{% extends 'fittings/base.html' %}

{% block subtitle %}Delete {{ fit.ship_name }}{% endblock %}

{% block body %}
<div class="page-header">
    <h1>{{ fit.comp.name }} <small>{{ fit.ship_name }}</small></h1>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="alert alert-danger" role="alert">
      Are you sure that you would like the delete the following Fit?
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <pre>{{ fit.eft_fit }}</pre>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <form action="" method="post">
      {% csrf_token %}
      <a href="{% url 'fittings:fit-edit' fit.comp.id fit.id %}" class="btn btn-default">Cancel</a>
      <button class="btn btn-danger pull-right" type="submit">Confirm <i class="fa fa-trash-o fa-lg"></i></button>
    </form>
  </div>
</div>
{% endblock %}

iron_at/templates/fittings/fit_form.html
{% extends 'fittings/base.html' %}
{% load bootstrap3 %}

{% block subtitle %}{{ composition.name }} – {% if fit %}Edit{% else %}Create{% endif %} Fit{% endblock %}

{% block body %}
<div class="page-header">
  {% if fit %}
  <h1>{{ composition.name }} <small>Update fit</small></h1>
  {% else %}
  <h1>{{ composition.name }} <small>Create fit</small>
  {% endif %}
</div>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="row">
    <div class="col-md-6">
      {% bootstrap_field field %}
    </div>
  </div>
  {% endfor %}
  {{ skills_formset.management_form}}
  <div id="skills-form-template" hidden="true">
    <div class= "row">
      <div class="col-md-6">
        {% bootstrap_form skills_formset.empty_form %}
      </div>
    </div>
  </div>
  {% for skills_formset_row in skills_formset %}
  <div class="skills-form row">
    <div class="col-md-6">
      {% bootstrap_form skills_formset_row %}
    </div>
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-md-6">
      <a href="{% url 'fittings:index' %}" class="btn btn-default">Cancel</a>
      <div class="pull-right">
        {% if fit %}
        <a href="{% url 'fittings:fit-delete' composition.id fit.id %}" class="btn btn-danger">
          <i class="fa fa-trash-o fa-lg"></i> Delete
        </a>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</form>
{% endblock %}

iron_at/templates/fittings/index.html
{% extends 'fittings/base.html' %}

{% block subtitle %}Fleet Comps{% endblock %}

{% block body %}
<div class="page-header">
  <h1>Iron AT Fleet Compositions</h1>
</div>
<div class="row">
  {% for comp in object_list %}
  <div class="col-md-4">
    <div class="list-group">
      <a href="{% url 'fittings:composition-details' comp.id %}"
          class="list-group-item"><h4 class="list-group-item-heading">{{ comp.name }}</h4></a>
      {% for fit in comp.fits.all %}
      <a href="{% url 'fittings:composition-details' comp.id %}" class="list-group-item">
        {{ fit.ship_name}}{% if fit.quantity > 1 %}<span class="badge">{{ fit.quantity }}</span>{% endif %}
      </a>
    {% endfor %}
    </div>
  </div>
  {% endfor %}
</div>
<div class="row">
  <div class="col-md-12">
    <a href="{% url 'fittings:composition-create' %}">add fleet comp</a>
  </div>
</div>
{% endblock %}

iron_at/templates/fittings/xup.html
{% extends 'fittings/base.html' %}
{% load bootstrap3 %}

{% block subtitle %}X Up{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{{ fit.comp.name }} <small>{{ fit.ship_name }}</small></h1>
</div>
<div class="row">
  <div class="col-md-5">
    <pre>{{ fit.eft_fit }}</pre>
  </div>
  <div class="col-md-6 col-md-offset-1">
    <div class="row">
      <div class="col-md-12">
        <h3>X Up</h3>
      </div>
    </div>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
      <div class="row">
        <div class="col-md-12">
          {% bootstrap_field field %}
        </div>
      </div>
      {% endfor %}
      <div class="row">
        <div class="col-md-12">
          <a href="{% url 'fittings:composition-details' fit.comp.id %}" class="btn btn-default" role="Cancel">
            Cancel
          </a>
          <button type="submit" class="btn btn-primary pull-right">Submit</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}